## 1. Project Setup

The project root directory is added to Python's import path so that the project's custom modules can be imported.

The required functions for loading and preprocessing the Titanic dataset are then imported from the `src` package.

In [23]:
from sklearn.base import BaseEstimator,TransformerMixin
import sys
from pathlib import Path

In [24]:
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

## 2. Load Train and Test Data

The Titanic dataset contains two separate files: `train.csv` and `test.csv`.

The training dataset contains the target variable `Survived`, while the test dataset does not contain this column.

Both datasets are loaded separately and will be preprocessed using the same transformations.

In [25]:
from src.data_loader import *
df_train=load_train_data()
df_test=load_test_data()

In [26]:
df_train.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [27]:
df_test.head()

   PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

## 3. Initial Data Inspection

Before applying preprocessing techniques, the structure of the training and test datasets is inspected.

The data types and missing values are checked to identify columns that require further preprocessing.

In [28]:
print(f'Train missing values\n')
print(df_train.isnull().sum())
print(f'\nTest missing values\n')
print(df_test.isnull().sum())

Train missing values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Test missing values

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

## 4.Preprocessing

The preprocessing functions and classes are implemented in the `src/preprocessing.py` module.

In this notebook, the `preprocess_data()` function is imported from `preprocessing.py` and used to apply the preprocessing pipeline to the Titanic datasets.

The preprocessing pipeline consists of three main classes:

* **`AgeImputer`** — handles missing values in the `Age` column using the mean value.
* **`FeatureEncoder`** — applies One-Hot Encoding to the `Embarked` and `Sex` categorical features.
* **`FeaturesDropper`** — removes unnecessary features such as `Name`, `Ticket`, `Fare`, `Cabin`, `Sex`, and `Embarked`.

These preprocessing steps are combined into a single `Pipeline` inside the `preprocess_data()` function.

The processed training and test datasets are then saved using the `save_processed_train()` and `save_processed_test()` functions.

```text
raw train/test data
        ↓
   preprocess_data()
        ↓
    AgeImputer
        ↓
  FeatureEncoder
        ↓
 FeaturesDropper
        ↓
processed train/test data
```

In [29]:
from src.preprocessing import preprocess_data,save_processed_train, save_processed_test
clean_df_train=preprocess_data(df_train)

In [30]:
clean_df_train

     PassengerId  Survived  Pclass        Age  ...    S    Q  Female  Male
0              1         0       3  22.000000  ...  0.0  1.0     0.0   1.0
1              2         1       1  38.000000  ...  0.0  0.0     1.0   0.0
2              3         1       3  26.000000  ...  0.0  1.0     1.0   0.0
3              4         1       1  35.000000  ...  0.0  1.0     1.0   0.0
4              5         0       3  35.000000  ...  0.0  1.0     0.0   1.0
..           ...       ...     ...        ...  ...  ...  ...     ...   ...
886          887         0       2  27.000000  ...  0.0  1.0     0.0   1.0
887          888         1       1  19.000000  ...  0.0  1.0     1.0   0.0
888          889         0       3  29.699118  ...  0.0  1.0     1.0   0.0
889          890         1       1  26.000000  ...  0.0  0.0     0.0   1.0
890          891         0       3  32.000000  ...  1.0  0.0     0.0   1.0

[891 rows x 11 columns]

In [31]:
clean_df_test=preprocess_data(df_test)

In [32]:
clean_df_test

     PassengerId  Pclass       Age  SibSp  Parch    C    S    Q  Female  Male
0            892       3  34.50000      0      0  0.0  1.0  0.0     0.0   1.0
1            893       3  47.00000      1      0  0.0  0.0  1.0     1.0   0.0
2            894       2  62.00000      0      0  0.0  1.0  0.0     0.0   1.0
3            895       3  27.00000      0      0  0.0  0.0  1.0     0.0   1.0
4            896       3  22.00000      1      1  0.0  0.0  1.0     1.0   0.0
..           ...     ...       ...    ...    ...  ...  ...  ...     ...   ...
413         1305       3  30.27259      0      0  0.0  0.0  1.0     0.0   1.0
414         1306       1  39.00000      0      0  1.0  0.0  0.0     1.0   0.0
415         1307       3  38.50000      0      0  0.0  0.0  1.0     0.0   1.0
416         1308       3  30.27259      0      0  0.0  0.0  1.0     0.0   1.0
417         1309       3  30.27259      1      1  1.0  0.0  0.0     0.0   1.0

[418 rows x 10 columns]

## 5. Final Data Validation

The processed training and test datasets are inspected to verify their structure, feature columns, and data types.

The final validation also checks that missing values have been handled successfully and that both datasets are ready for the modeling and prediction stages.

In [33]:
clean_df_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
C              0
S              0
Q              0
Female         0
Male           0
dtype: int64

In [34]:
clean_df_test.isnull().sum()

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
C              0
S              0
Q              0
Female         0
Male           0
dtype: int64

## 6.Save Preprocessed Datasets

The processed training and test datasets are saved as CSV files using the `save_processed_train()` and `save_processed_test()` functions from the `src/preprocessing.py` module.

The processed datasets are saved separately in the `data/processed/` directory and are used in the modeling and prediction stages.

In [37]:
save_processed_train(clean_df_train)
save_processed_test(clean_df_test)