# Titanic Survival Prediction — Model Training & Evaluation

This notebook focuses on training, hyperparameter tuning, evaluating, and comparing machine learning classification models for the Titanic Survival Prediction project.

## Objectives

The main objectives of this notebook are:

Load the preprocessed training and test datasets.
Split the training data into training and validation sets.
Train multiple classification models.
Tune model hyperparameters using GridSearchCV.
Evaluate each model using classification metrics.
Compare model performance.
Select the best-performing model based on accuracy.
Save the selected model for future predictions.

## 1. Libraries

The required Python libraries are imported for:

- Data manipulation
- Model training
- Hyperparameter tuning
- Model evaluation
- Model serialization

In [1]:
import sys
from pathlib import Path
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [2]:
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

## 2. Load Processed Data

The processed datasets generated during the preprocessing stage are loaded from the data/processed/ directory.

The training dataset contains the Survived target variable, while the test dataset is used for generating final predictions.

In [3]:
from src.data_loader import load_preprocessed_train,load_preprocessed_test
from src.train  import *
df_train=load_preprocessed_train()
df_test=load_preprocessed_test()

In [4]:
df_train.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,C,S,Q,Female,Male
0,1,0,3,22.0,1,0,7.2500,0.0,0.0,1.0,0.0,1.0
1,2,1,1,38.0,1,0,71.2833,1.0,0.0,0.0,1.0,0.0
2,3,1,3,26.0,0,0,7.9250,0.0,0.0,1.0,1.0,0.0
3,4,1,1,35.0,1,0,53.1000,0.0,0.0,1.0,1.0,0.0
4,5,0,3,35.0,0,0,8.0500,0.0,0.0,1.0,0.0,1.0

In [5]:
df_test.head()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,C,S,Q,Female,Male
0,892,3,34.5,0,0,7.8292,0.0,1.0,0.0,0.0,1.0
1,893,3,47.0,1,0,7.0000,0.0,0.0,1.0,1.0,0.0
2,894,2,62.0,0,0,9.6875,0.0,1.0,0.0,0.0,1.0
3,895,3,27.0,0,0,8.6625,0.0,0.0,1.0,0.0,1.0
4,896,3,22.0,1,1,12.2875,0.0,0.0,1.0,1.0,0.0

## 3. Split the Data

The `split_data()` function is imported from the `train.py` module located in the `src/` directory.

This function is used to split the training dataset into training and test subsets:

```python
x_train, x_test, y_train, y_test = split_data(df_train)
```

The function returns:

* `x_train` — Features used for model training
* `x_test` — Features used for model evaluation
* `y_train` — Target values for the training set
* `y_test` — Target values for the test set

The `Survived` column is used as the target variable.

The resulting datasets are passed to the machine learning models for training, hyperparameter tuning, and evaluation.

In [7]:
x_train,x_test,y_train,y_test=split_data(df_train)

In [8]:
x_train

,PassengerId,Pclass,Age,SibSp,Parch,Fare,C,S,Q,Female,Male
709,710,3,29.699118,1,1,15.2458,1.0,0.0,0.0,0.0,1.0
439,440,2,31.000000,0,0,10.5000,0.0,0.0,1.0,0.0,1.0
840,841,3,20.000000,0,0,7.9250,0.0,0.0,1.0,0.0,1.0
720,721,2,6.000000,0,1,33.0000,0.0,0.0,1.0,1.0,0.0
39,40,3,14.000000,1,0,11.2417,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
433,434,3,17.000000,0,0,7.1250,0.0,0.0,1.0,0.0,1.0
773,774,3,29.699118,0,0,7.2250,1.0,0.0,0.0,0.0,1.0
25,26,3,38.000000,1,5,31.3875,0.0,0.0,1.0,1.0,0.0
84,85,2,17.000000,0,0,10.5000,0.0,0.0,1.0,1.0,0.0
10,11,3,4.000000,1,1,16.7000,0.0,0.0,1.0,1.0,0.0

In [9]:

y_train

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1])

In [10]:
x_test

,PassengerId,Pclass,Age,SibSp,Parch,Fare,C,S,Q,Female,Male
331,332,1,45.500000,0,0,28.5000,0.0,0.0,1.0,0.0,1.0
733,734,2,23.000000,0,0,13.0000,0.0,0.0,1.0,0.0,1.0
382,383,3,32.000000,0,0,7.9250,0.0,0.0,1.0,0.0,1.0
704,705,3,26.000000,1,0,7.8542,0.0,0.0,1.0,0.0,1.0
813,814,3,6.000000,4,2,31.2750,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
106,107,3,21.000000,0,0,7.6500,0.0,0.0,1.0,1.0,0.0
270,271,1,29.699118,0,0,31.0000,0.0,0.0,1.0,0.0,1.0
860,861,3,41.000000,2,0,14.1083,0.0,0.0,1.0,0.0,1.0
435,436,1,14.000000,1,2,120.0000,0.0,0.0,1.0,1.0,0.0
102,103,1,21.000000,0,1,77.2875,0.0,0.0,1.0,0.0,1.0

In [11]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0])

## 4. Feature Scaling

The `standardisation()` function from `src/train.py` is used to standardize the features for Logistic Regression.

```python
x_train_scaled, x_test_scaled = standardisation(x_train, x_test)
```

The scaler is fitted on the training data and then applied to the test data.

In [12]:
x_train_scaled,x_test_scaled=standardisation(x_train,x_test)

In [13]:
x_train_scaled

array([[ 1.05110212,  0.88742288, -0.04918352, ..., -1.40830868,
        -0.79200551,  0.79200551],
       [ 0.01112494, -0.25537349,  0.05079242, ...,  0.7100716 ,
        -0.79200551,  0.79200551],
       [ 1.55568365,  0.88742288, -0.79458411, ...,  0.7100716 ,
        -0.79200551,  0.79200551],
       ...,
       [-1.58350675,  0.88742288,  0.58875931, ...,  0.7100716 ,
         1.26261748, -1.26261748],
       [-1.35625248, -0.25537349, -1.02514134, ...,  0.7100716 ,
         1.26261748, -1.26261748],
       [-1.64128326,  0.88742288, -2.0242227 , ...,  0.7100716 ,
         1.26261748, -1.26261748]])

In [14]:
x_test_scaled

array([[-0.40486594, -1.39816986,  1.1651524 , ...,  0.7100716 ,
        -0.79200551,  0.79200551],
       [ 1.14354454, -0.25537349, -0.56402687, ...,  0.7100716 ,
        -0.79200551,  0.79200551],
       [-0.2084258 ,  0.88742288,  0.12764484, ...,  0.7100716 ,
        -0.79200551,  0.79200551],
       ...,
       [ 1.632719  ,  0.88742288,  0.81931654, ...,  0.7100716 ,
        -0.79200551,  0.79200551],
       [-0.00428213, -1.39816986, -1.25569858, ...,  0.7100716 ,
         1.26261748, -1.26261748],
       [-1.28692066, -1.39816986, -0.7177317 , ...,  0.7100716 ,
        -0.79200551,  0.79200551]])

## 5. Model Training

Three classification models are trained and tuned using `GridSearchCV`:

* Random Forest Classifier
* Decision Tree Classifier
* Logistic Regression

The `train_model()` function, defined in `src/train.py`, is used to train and tune all three models.

Random Forest and Decision Tree are trained using the original features, while Logistic Regression is trained using the standardized features.

The performance of each model is evaluated using accuracy.

### RandomForestClassifier

In [15]:
rd_model=RandomForestClassifier(random_state=42,n_jobs=-1)
rd_param_grid={'n_estimators':[100,200],
               'max_depth':[5,6,10,None],
               'min_samples_split':[2,5,10]
               ,'min_samples_leaf':[1,2,4],
               'max_features':['log2','sqrt']}
best_rf,predictions_rf,acc_rf=train_model(rd_model,rd_param_grid,x_train,x_test,y_train,y_test)

In [16]:
print(f'RandomForestClassifier accuracy: {acc_rf}')

RandomForestClassifier accuracy: 0.800561797752809

### DecisionTreeClassifier

In [17]:
dt=DecisionTreeClassifier(random_state=42)
dt_param_grid={'max_depth':[5,6,8,None],
               'min_samples_split':[2,5,10]
               ,'min_samples_leaf':[2,4,5],
               'max_features':['log2','sqrt']}
best_dt,params_dt,acc_dt=train_model(dt,dt_param_grid,x_train,x_test,y_train,y_test)

In [18]:
print(f'Accuracy DecisionTree is {acc_dt}')

Accuracy DecisionTree is 0.7528089887640449

### LogesticRegression

In [19]:
log_reg=LogisticRegression(solver='liblinear',random_state=42)
log_reg_params={'C':[0.001,0.01,0.1,1],
                'penalty':['l1','l2']}
best_log_reg,predictions_log_reg,acc_log_reg=train_model(log_reg,log_reg_params,x_train_scaled,x_test_scaled,y_train,y_test)
# best_log_reg,predictions_log_reg,acc_log_reg=logestic_model(log_reg,log_reg_params,x_train_scaled,x_test_scaled,y_train,y_test)

In [20]:
print(f'Accuracy Logesticregression :{acc_log_reg}')

Accuracy Logesticregression :0.800561797752809

## 6. Model Comparison

The performance of the three trained models is compared based on accuracy.

The models are sorted in descending order to make the performance comparison easier.

In [21]:
comparison = pd.DataFrame({
    "Model": ["Random Forest", "Decision Tree","Logestic Regression"],
    "Accuracy":[acc_rf,acc_dt,acc_log_reg]
    
})

comparison = comparison.sort_values("Accuracy", ascending=False)
comparison

                 Model  Accuracy
0        Random Forest  0.800562
2  Logestic Regression  0.800562
1        Decision Tree  0.752809

## 7. Best Model Selection and Saving

The model with the highest accuracy is selected from the trained models.

The selected model is then saved using `joblib` to:

```text
models/model.pkl
```

This allows the best model to be loaded and reused later without retraining.

In [22]:
import joblib

MODEL_PATH = PROJECT_ROOT / "models" / "model.pkl"

models = {
    "Random Forest": (best_rf, acc_rf),
    "Desicion Tree": (best_dt, acc_dt),
    "logestic_model":(best_log_reg,acc_log_reg)
}

best_name, (best_model, best_accuracy) = max(
    models.items(),
    key=lambda x: x[1][1]
)

joblib.dump(best_model, MODEL_PATH)

print(f"Best model: {best_name}")
print(f"Accuracy : {best_accuracy:.4f}")
print(f"Model saved to: {MODEL_PATH}")

Best model: Random Forest
Accuracy : 0.8006
Model saved to: c:\Users\Asus\titanic\models\model.pkl

In [27]:
predictions_test=best_rf.predict(df_test)
predictions_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

## 8. Check Saved Model

The code checks whether the trained model file exists in the `models/model.pkl` path.

If the file exists, its path is displayed.

In [24]:
if MODEL_PATH.exists():
    print('Model file exist !')
    print(f'path : {MODEL_PATH}')

Model file exist !
path : c:\Users\Asus\titanic\models\model.pkl

## 9. Load Model and Generate Predictions

The saved model is loaded using the functions defined in `src/predict.py`.

The loaded model is then used to generate predictions on the test data.

The first five predictions are displayed to verify the prediction results.

In [25]:
from src.predict import *
from src.data_loader import load_train_data
from src.predict import predict

model = load_model()

predictions = predict(model, x_test)

print(predictions[:5])

[0 0 0 0 0]

##  10. Generate Submission File

The predictions are combined with the `PassengerId` column to create the final submission file.

The file is saved as `predictions.csv` in the `data/submission/` directory.

In [28]:
path_submission=PROJECT_ROOT/'data'/'submission'/'predictions.csv'
submission=pd.DataFrame({"PassengerId":df_test['PassengerId'],
                        'Survived':predictions_test
                       })
submission.to_csv(path_submission,index=False)